#READ THE DATA FILES
b2_fpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch2_fpon_0.txt", header=FALSE, sep="\t", dec=".")
b2_mpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch2_mpon_0.txt", header=FALSE, sep="\t", dec=".")
b3_fpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch3_fpon_0.txt", header=FALSE, sep="\t", dec=".")
b3_mpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch3_mpon_0.txt", header=FALSE, sep="\t", dec=".")
b3_fpon_1 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch3_fpon_1.txt", header=FALSE, sep="\t", dec=".")
b3_mpon_1 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch3_mpon_1.txt", header=FALSE, sep="\t", dec=".")
b4_fpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch4_fpon_0.txt", header=FALSE, sep="\t", dec=".")
b4_mpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch4_mpon_0.txt", header=FALSE, sep="\t", dec=".")
b4_fpon_1 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch4_fpon_1.txt", header=FALSE, sep="\t", dec=".")
b4_mpon_1 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch4_mpon_1.txt", header=FALSE, sep="\t", dec=".")
b10_fpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch10_fpon_0.txt", header=FALSE, sep="\t", dec=".")
b10_mpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch10_mpon_0.txt", header=FALSE, sep="\t", dec=".")
b11_fpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch11_fpon_0.txt", header=FALSE, sep="\t", dec=".")
b11_mpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch11_mpon_0.txt", header=FALSE, sep="\t", dec=".")
b11_fpon_1 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch11_fpon_1.txt", header=FALSE, sep="\t", dec=".")
b11_mpon_1 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch11_mpon_1.txt", header=FALSE, sep="\t", dec=".")
b12_fpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch12_fpon_0.txt", header=FALSE, sep="\t", dec=".")
b12_mpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch12_mpon_0.txt", header=FALSE, sep="\t", dec=".")
b16_fpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch16_fpon_0.txt", header=FALSE, sep="\t", dec=".")
b16_mpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch16_mpon_0.txt", header=FALSE, sep="\t", dec=".")
b16_fpon_1 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch16_fpon_1.txt", header=FALSE, sep="\t", dec=".")
b16_mpon_1 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch16_mpon_1.txt", header=FALSE, sep="\t", dec=".")
b16_fpon_2 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch16_fpon_2.txt", header=FALSE, sep="\t", dec=".")
b16_mpon_2 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch16_mpon_2.txt", header=FALSE, sep="\t", dec=".")
b16_fpon_3 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch16_fpon_3.txt", header=FALSE, sep="\t", dec=".")
b16_mpon_3 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch16_mpon_3.txt", header=FALSE, sep="\t", dec=".")
b16_fpon_4 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch16_fpon_4.txt", header=FALSE, sep="\t", dec=".")
b16_mpon_4 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch16_mpon_4.txt", header=FALSE, sep="\t", dec=".")
b16_fpon_5 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch16_fpon_5.txt", header=FALSE, sep="\t", dec=".")
b16_mpon_5 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch16_mpon_5.txt", header=FALSE, sep="\t", dec=".")
b16_fpon_6 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch16_fpon_6.txt", header=FALSE, sep="\t", dec=".")
b16_mpon_6 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch16_mpon_6.txt", header=FALSE, sep="\t", dec=".")
b16_fpon_7 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch16_fpon_7.txt", header=FALSE, sep="\t", dec=".")
b16_mpon_7 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch16_mpon_7.txt", header=FALSE, sep="\t", dec=".")
b17_fpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch17_fpon_0.txt", header=FALSE, sep="\t", dec=".")
b17_mpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch17_mpon_0.txt", header=FALSE, sep="\t", dec=".")
b17_fpon_1 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch17_fpon_1.txt", header=FALSE, sep="\t", dec=".")
b17_mpon_1 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch17_mpon_1.txt", header=FALSE, sep="\t", dec=".")
b17_fpon_2 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch17_fpon_2.txt", header=FALSE, sep="\t", dec=".")
b17_mpon_2 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch17_mpon_2.txt", header=FALSE, sep="\t", dec=".")
b17_fpon_3 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch17_fpon_3.txt", header=FALSE, sep="\t", dec=".")
b17_mpon_3 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch17_mpon_3.txt", header=FALSE, sep="\t", dec=".")
b17_fpon_4 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch17_fpon_4.txt", header=FALSE, sep="\t", dec=".")
b17_mpon_4 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch17_mpon_4.txt", header=FALSE, sep="\t", dec=".")
b17_fpon_5 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch17_fpon_5.txt", header=FALSE, sep="\t", dec=".")
b17_mpon_5 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch17_mpon_5.txt", header=FALSE, sep="\t", dec=".")
b17_fpon_6 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch17_fpon_6.txt", header=FALSE, sep="\t", dec=".")
b17_mpon_6 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch17_mpon_6.txt", header=FALSE, sep="\t", dec=".")
b17_fpon_7 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch17_fpon_7.txt", header=FALSE, sep="\t", dec=".")
b17_mpon_7 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch17_mpon_7.txt", header=FALSE, sep="\t", dec=".")
b18_fpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch18_fpon_0.txt", header=FALSE, sep="\t", dec=".")
b18_mpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch18_mpon_0.txt", header=FALSE, sep="\t", dec=".")
b18_fpon_1 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch18_fpon_1.txt", header=FALSE, sep="\t", dec=".")
b18_mpon_1 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch18_mpon_1.txt", header=FALSE, sep="\t", dec=".")
b19_fpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch19_fpon_0.txt", header=FALSE, sep="\t", dec=".")
b19_mpon_0 <- read.table("H:\\data\\tmp3\\solverd\\documentation\\pon\\pon_svds\\svd_batch19_mpon_0.txt", header=FALSE, sep="\t", dec=".")


#MAKE THE PLOT COLOURS LISTS
b2colours <- rainbow(2)
b3colours <- rainbow(4)
b4colours <- rainbow(4)
b10colours <- rainbow(2)
b11colours <- rainbow(4)
b12colours <- rainbow(2)
b16colours <- rainbow(16)
b17colours <- rainbow(16)
b18colours <- rainbow(4)
b19colours <- rainbow(2)

#MAKE THE LEGEND LABELS
b2legend <- c("female PoN 0", "male PoN 0")
b3legend <- c("female PoN 0", "male PoN 0", "female PoN 1", "male PoN 1")
b4legend <- c("female PoN 0", "male PoN 0", "female PoN 1", "male PoN 1")
b10legend <- c("female PoN 0", "male PoN 0")
b11legend <- c("female PoN 0", "male PoN 0", "female PoN 1", "male PoN 1")
b12legend <- c("female PoN 0", "male PoN 0")
b16legend <- c("female PoN 0", "male PoN 0", "female PoN 1", "male PoN 1", "female PoN 2", "male PoN 2", "female PoN 3", "male PoN 3", "female PoN 4", "male PoN 4", "female PoN 5", "male PoN 5",  "female PoN 6", "male PoN 6", "female PoN 7", "male PoN 7")
b17legend <- c("female PoN 0", "male PoN 0", "female PoN 1", "male PoN 1", "female PoN 2", "male PoN 2", "female PoN 3", "male PoN 3", "female PoN 4", "male PoN 4", "female PoN 5", "male PoN 5",  "female PoN 6", "male PoN 6", "female PoN 7", "male PoN 7")
b18legend <- c("female PoN 0", "male PoN 0", "female PoN 1", "male PoN 1")
b19legend <- c("female PoN 0", "male PoN 0")


#Make the plots
#par(mfrow=c(4,2))
plot(b2_fpon_0[,1], type="l", main="Batch 2", xlab="SVD", ylab="SVD value", col=b2colours[1], lwd=2, ylim=c(0,1200))
lines(b2_mpon_0[,1], col=b2colours[2], lwd=2)
legend("topright", legend=b2legend, fill=b2colours)

plot(b3_fpon_0[,1], type="l", main="Batch 3", xlab="SVD", ylab="SVD value", col=b3colours[1], lwd=2, ylim=c(0,2800))
lines(b3_mpon_0[,1], col=b3colours[2], lwd=2)
lines(b3_fpon_1[,1], col=b3colours[3], lwd=2)
lines(b3_mpon_1[,1], col=b3colours[4], lwd=2)
legend("topright", legend=b3legend, fill=b3colours)

plot(b4_fpon_0[,1], type="l", main="Batch 4", xlab="SVD", ylab="SVD value", col=b4colours[1], lwd=2, ylim=c(0,1600))
lines(b4_mpon_0[,1], col=b4colours[2], lwd=2)
lines(b4_fpon_1[,1], col=b4colours[3], lwd=2)
lines(b4_mpon_1[,1], col=b4colours[4], lwd=2)
legend("topright", legend=b4legend, fill=b4colours)

plot(b10_fpon_0[,1], type="l", main="Batch 10", xlab="SVD", ylab="SVD value", col=b10colours[1], lwd=2, ylim=c(0,1200))
lines(b10_mpon_0[,1], col=b10colours[2], lwd=2)
legend("topright", legend=b10legend, fill=b10colours)

plot(b11_fpon_0[,1], type="l", main="Batch 11", xlab="SVD", ylab="SVD value", col=b11colours[1], lwd=2, ylim=c(0,1700))
lines(b11_mpon_0[,1], col=b11colours[2], lwd=2)
lines(b11_fpon_1[,1], col=b11colours[3], lwd=2)
lines(b11_mpon_1[,1], col=b11colours[4], lwd=2)
legend("topright", legend=b11legend, fill=b11colours)

plot(b12_fpon_0[,1], type="l", main="Batch 12", xlab="SVD", ylab="SVD value", col=b12colours[1], lwd=2, ylim=c(0,1700))
lines(b12_mpon_0[,1], col=b12colours[2], lwd=2)
legend("topright", legend=b12legend, fill=b12colours)

plot(b16_fpon_0[,1], type="l", main="Batch 16", xlab="SVD", ylab="SVD value", col=b16colours[1], lwd=2, ylim=c(0,1600))
lines(b16_mpon_0[,1], col=b16colours[2], lwd=2)
lines(b16_fpon_1[,1], col=b16colours[3], lwd=2)
lines(b16_mpon_1[,1], col=b16colours[4], lwd=2)
lines(b16_fpon_2[,1], col=b16colours[5], lwd=2)
lines(b16_mpon_2[,1], col=b16colours[6], lwd=2)
lines(b16_fpon_3[,1], col=b16colours[7], lwd=2)
lines(b16_mpon_3[,1], col=b16colours[8], lwd=2)
lines(b16_fpon_4[,1], col=b16colours[9], lwd=2)
lines(b16_mpon_4[,1], col=b16colours[10], lwd=2)
lines(b16_fpon_5[,1], col=b16colours[11], lwd=2)
lines(b16_mpon_5[,1], col=b16colours[12], lwd=2)
lines(b16_fpon_6[,1], col=b16colours[13], lwd=2)
lines(b16_mpon_6[,1], col=b16colours[14], lwd=2)
lines(b16_fpon_7[,1], col=b16colours[15], lwd=2)
lines(b16_mpon_7[,1], col=b16colours[16], lwd=2)
legend("topright", legend=b16legend, fill=b16colours)

plot(b18_fpon_0[,1], type="l", main="Batch 18", xlab="SVD", ylab="SVD value", col=b18colours[1], lwd=2, ylim=c(0,1500))
lines(b18_mpon_0[,1], col=b18colours[2], lwd=2)
lines(b18_fpon_1[,1], col=b18colours[3], lwd=2)
lines(b18_mpon_1[,1], col=b18colours[4], lwd=2)
legend("topright", legend=b18legend, fill=b18colours)

plot(b19_fpon_0[,1], type="l", main="Batch 19", xlab="SVD", ylab="SVD value", col=b19colours[1], lwd=2, ylim=c(0,1000))
lines(b19_mpon_0[,1], col=b19colours[2], lwd=2)
legend("topright", legend=b19legend, fill=b19colours)

